name: Jira Sync
on:
  push:
    branches:
      - main
jobs:
  sync-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to Jira
        uses: atlassian/gajira-create@v3
        with:
          jira-url: "https://your-jira-instance.atlassian.net"
          jira-user: "${{ secrets.JIRA_USER }}"
          jira-api-token: "${{ secrets.JIRA_API_TOKEN }}"
          project: "MAZ"
